# Generated by Django 4.1.3 on 2022-12-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AddEvent", models.CharField(blank=True, default="", max_length=50)),
                ("Date", models.DateField()),
            ],
            options={"db_table": "Event",},
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddNotices",
                    models.TextField(blank=True, default="", max_length=150),
                ),
                ("Date", models.DateField()),
            ],
            options={"db_table": "Notice",},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "Transaction",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
            ],
            options={"db_table": "User",},
        ),
        migrations.CreateModel(
            name="Watchman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=20)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_App.user",
                    ),
                ),
            ],
            options={"db_table": "Watchman",},
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=20)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_App.user",
                    ),
                ),
            ],
            options={"db_table": "Visitor",},
        ),
        migrations.CreateModel(
            name="Notice_view",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Notices",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_App.notice",
                    ),
                ),
            ],
            options={"db_table": "Notice_view",},
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=15)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Male"), ("f", "Female")],
                        default="",
                        max_length=6,
                    ),
                ),
                ("Birthday", models.DateField(default="2022-11-20")),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_App.user",
                    ),
                ),
            ],
            options={"db_table": "Member",},
        ),
        migrations.CreateModel(
            name="Chairman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=15)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Male"), ("f", "Female")],
                        default="",
                        max_length=6,
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_App.user",
                    ),
                ),
            ],
            options={"db_table": "Chairman",},
        ),
    ]
