# Generated by Django 4.1.3 on 2023-01-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0003_alter_role_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairman",
            name="Type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="chairman",
            name="Visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="digital_App.visitor"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="Visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="digital_App.visitor"
            ),
        ),
    ]
