# Generated by Django 4.1.3 on 2023-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0004_chairman_type_alter_chairman_visitor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="HouseNO",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
