# Generated by Django 4.1.3 on 2023-01-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0005_member_houseno"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="HouseNO",),
    ]
